package com.chatapp.modules.myclouds.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;

@DynamoDBTable(tableName = "MyCloud")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class MyCloud {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "userId-uploadAt-index")
    @DynamoDBAttribute(attributeName = "user_id")
    private String userId;

    @DynamoDBAttribute(attributeName = "file_name")
    private String fileName;

    @DynamoDBAttribute(attributeName = "s3_key")
    private String s3Key;

    @DynamoDBAttribute(attributeName = "file_url")
    private String fileUrl;

    /**  image| video| audio| document| other **/
    @DynamoDBAttribute(attributeName = "type_file")
    private String typeFile;

    /** Mime type gốc: image/png, video/mp4....**/
    @DynamoDBAttribute(attributeName = "mime_type")
    private String mimeType;


    /** Kích thước file tính bằng bytes */
    @DynamoDBAttribute(attributeName = "file_size")
    private Long fileSize;

    /** Dùng cho phân trang theo thời gian trên GSI */
    @DynamoDBIndexRangeKey(globalSecondaryIndexName = "userId-uploadedAt-index")
    @DynamoDBAttribute(attributeName = "uploaded_at")
    private String uploadedAt; // ISO-8601 string để sort được trên DynamoDB

    @DynamoDBAttribute(attributeName = "created_at")
    private String createdAt;

    /** soft-delete: true khi user xoá */
    @DynamoDBAttribute(attributeName = "is_deleted")
    private boolean deleted;
}
