package com.chatapp.modules.notification.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.NotNull;
import lombok.*;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ToString
@DynamoDBTable(tableName = "Notification")
public class Notification {
    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBIndexHashKey(
            globalSecondaryIndexName = "senderId-index",
            attributeName = "senderId"
    )
    private String senderId;

    @DynamoDBIndexHashKey(
            globalSecondaryIndexName = "receiverId-index",
            attributeName = "receiverId"
    )
    private String receiverId;

    @DynamoDBTypeConverted(converter = NotificationTypeConverter.class)
    @DynamoDBAttribute(attributeName = "type")
    private NotificationType type;

    @DynamoDBAttribute(attributeName = "message")
    private String message;

    @DynamoDBAttribute(attributeName = "isRead")
    private boolean isRead;

    @DynamoDBAttribute(attributeName = "createdAt")
    private Long createdAt;
}