package com.chatapp.modules.conversation.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.List;
import java.util.Set;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "chat_conversations")
public class Conversation {

    @DynamoDBHashKey(attributeName = "conversationId")
    @DynamoDBAutoGeneratedKey
    private String conversationId;

    @DynamoDBAttribute(attributeName = "type")
    private String type; // SINGLE, GROUP

    @DynamoDBAttribute(attributeName = "name")
    private String name;

    @DynamoDBAttribute(attributeName = "avatarUrl")
    private String avatarUrl;

    @DynamoDBAttribute(attributeName = "creatorId")
    private String creatorId;

    @DynamoDBAttribute(attributeName = "lastMessage")
    private String lastMessage;

    @DynamoDBAttribute(attributeName = "lastMessageTime")
    private Long lastMessageTime;

    @DynamoDBAttribute(attributeName = "createdAt")
    private Long createdAt;

    @DynamoDBAttribute(attributeName = "updatedAt")
    private Long updatedAt;

    @DynamoDBAttribute(attributeName = "memberIds")
    private Set<String> memberIds; // Set of user IDs for easy querying if needed

    @DynamoDBAttribute(attributeName = "pinnedMessageIds")
    private Set<String> pinnedMessageIds;
}
