package com.chatapp.modules.conversation.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "chat_group_join_requests")
public class GroupJoinRequest {

    @DynamoDBHashKey(attributeName = "requestId")
    @DynamoDBAutoGeneratedKey
    private String requestId;

    @DynamoDBAttribute(attributeName = "userId")
    private String userId;

    @DynamoDBIndexHashKey(globalSecondaryIndexName = "conversation-index", attributeName = "conversationId")
    private String conversationId;

    @DynamoDBAttribute(attributeName = "status")
    private String status; // PENDING, APPROVED, REJECTED

    @DynamoDBAttribute(attributeName = "createdAt")
    private Long createdAt;
}
