package com.chatapp.modules.conversation.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "chat_group_invitations")
public class GroupInvitation {
    @DynamoDBHashKey(attributeName = "invitationId")
    @DynamoDBAutoGeneratedKey
    private String invitationId;

    @DynamoDBIndexHashKey(globalSecondaryIndexName = "invitee-index", attributeName = "inviteeId")
    private String inviteeId;

    @DynamoDBAttribute
    private String inviterId;

    @DynamoDBAttribute
    private String conversationId;

    @DynamoDBAttribute
    private String groupName;

    @DynamoDBAttribute
    private String status; // PENDING, ACCEPTED, REJECTED

    @DynamoDBAttribute
    private Long createdAt;
}
