package com.chatapp.modules.admin.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Admin System Log entity
 * Stored in DynamoDB
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "chat_admin_logs")
public class AdminSystemLog {

    @DynamoDBHashKey(attributeName = "logId")
    @DynamoDBAutoGeneratedKey
    private String logId;

    @DynamoDBAttribute(attributeName = "actionType")
    private String actionType; // e.g. "USER_LOCKED", "GROUP_CREATED", "USER_DELETED"

    @DynamoDBAttribute(attributeName = "description")
    private String description; // Detailed description of the action

    @DynamoDBAttribute(attributeName = "adminId")
    private String adminId; // User ID of the admin who performed the action (if applicable)

    @DynamoDBAttribute(attributeName = "adminName")
    private String adminName; // Name of the admin

    @DynamoDBAttribute(attributeName = "targetId")
    private String targetId; // User ID or Group ID that was affected

    @DynamoDBAttribute(attributeName = "targetName")
    private String targetName; // Name of the affected user/group

    @DynamoDBAttribute(attributeName = "createdAt")
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "createdAtIndex")
    private Long createdAt; // Timestamp
}
