package com.chatapp.modules.admin.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "chat_reports")
public class Report {

    @DynamoDBHashKey(attributeName = "reportId")
    @DynamoDBAutoGeneratedKey
    private String reportId;

    @DynamoDBAttribute(attributeName = "reporterId")
    private String reporterId;

    @DynamoDBAttribute(attributeName = "reporterName")
    private String reporterName;

    @DynamoDBAttribute(attributeName = "targetId")
    private String targetId;

    @DynamoDBAttribute(attributeName = "targetName")
    private String targetName;

    @DynamoDBAttribute(attributeName = "targetType")
    private String targetType; // USER, GROUP

    @DynamoDBAttribute(attributeName = "reason")
    private String reason;

    @DynamoDBAttribute(attributeName = "details")
    private String details;

    @DynamoDBAttribute(attributeName = "status")
    private String status; // PENDING, RESOLVED

    @DynamoDBAttribute(attributeName = "actionTaken")
    private String actionTaken; // WARNED, LOCKED, DISBANDED, DISMISSED

    @DynamoDBAttribute(attributeName = "createdAt")
    private Long createdAt;

    @DynamoDBAttribute(attributeName = "resolvedAt")
    private Long resolvedAt;
}
